# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AptBuilding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('allow_smocking', models.BooleanField(default=False)),
                ('room_num', models.IntegerField(default=4)),
                ('aptBuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptBuilding.AptBuilding')),
            ],
        ),
    ]
