# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Renter', '0001_initial'),
        ('Apt', '0001_initial'),
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_process', models.CharField(max_length=255)),
                ('price', models.FloatField(default=700)),
                ('deposit', models.FloatField(default=500)),
                ('apt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apt.Apt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.Owner')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Renter.Renter')),
            ],
        ),
    ]
